/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package guiforms;

/**
 *
 * @author my-pc
 */
public class DashboardsGui extends javax.swing.JFrame {

    /** Creates new form DashboardsGui */
    public DashboardsGui() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dashboardPanel = new javax.swing.JPanel();
        dashboardTabs = new javax.swing.JTabbedPane();
        appointmentsTab = new javax.swing.JPanel();
        aDateSeach = new javax.swing.JLabel();
        createAppointmentBtn = new javax.swing.JButton();
        aClientSearch = new javax.swing.JLabel();
        aClientField = new javax.swing.JTextField();
        aDateField = new javax.swing.JTextField();
        aSearchBtn = new javax.swing.JButton();
        aPetSearch = new javax.swing.JLabel();
        appointmentTableScroll = new javax.swing.JScrollPane();
        appointmentsTable = new javax.swing.JTable();
        aPetField = new javax.swing.JTextField();
        petsTab = new javax.swing.JPanel();
        createPetBtn = new javax.swing.JButton();
        pNameSearch = new javax.swing.JLabel();
        pDOBSearch = new javax.swing.JLabel();
        pClientField = new javax.swing.JTextField();
        pNameField = new javax.swing.JTextField();
        petTableScroll = new javax.swing.JScrollPane();
        petTable = new javax.swing.JTable();
        pClientSearch = new javax.swing.JLabel();
        pDOBField = new javax.swing.JTextField();
        pSearchBtn = new javax.swing.JButton();
        clientsTab = new javax.swing.JPanel();
        clientTableScroll = new javax.swing.JScrollPane();
        clientsTable = new javax.swing.JTable();
        createClientBtn = new javax.swing.JButton();
        cNameSearch = new javax.swing.JLabel();
        cEmailSearch = new javax.swing.JLabel();
        cNumberSearch = new javax.swing.JLabel();
        cSearchBtn = new javax.swing.JButton();
        cNameField = new javax.swing.JTextField();
        cEmailField = new javax.swing.JTextField();
        cNumberField = new javax.swing.JTextField();
        logoutBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dashboardPanel.setBackground(new java.awt.Color(255, 255, 255));
        dashboardPanel.setForeground(new java.awt.Color(41, 41, 41));

        dashboardTabs.setBackground(new java.awt.Color(255, 255, 255));
        dashboardTabs.setForeground(new java.awt.Color(38, 38, 38));
        dashboardTabs.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        appointmentsTab.setBackground(new java.awt.Color(255, 255, 255));
        appointmentsTab.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        aDateSeach.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        aDateSeach.setText("Date:");

        createAppointmentBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        createAppointmentBtn.setText("+ Create New Appointment");
        createAppointmentBtn.setToolTipText("");
        createAppointmentBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createAppointmentBtnMouseClicked(evt);
            }
        });

        aClientSearch.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        aClientSearch.setText("Client:");

        aClientField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        aDateField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        aSearchBtn.setBackground(new java.awt.Color(255, 255, 255));
        aSearchBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        aSearchBtn.setText("Search");
        aSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aSearchBtnActionPerformed(evt);
            }
        });

        aPetSearch.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        aPetSearch.setText("Pet:");

        appointmentTableScroll.setBackground(new java.awt.Color(255, 255, 255));

        appointmentsTable.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        appointmentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Date", "Time", "Client", "Pet", "Reason for Visit", "Actions"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        appointmentsTable.setGridColor(new java.awt.Color(255, 255, 255));
        appointmentTableScroll.setViewportView(appointmentsTable);
        if (appointmentsTable.getColumnModel().getColumnCount() > 0) {
            appointmentsTable.getColumnModel().getColumn(0).setResizable(false);
            appointmentsTable.getColumnModel().getColumn(1).setResizable(false);
            appointmentsTable.getColumnModel().getColumn(2).setResizable(false);
            appointmentsTable.getColumnModel().getColumn(3).setResizable(false);
            appointmentsTable.getColumnModel().getColumn(4).setResizable(false);
            appointmentsTable.getColumnModel().getColumn(5).setResizable(false);
        }

        aPetField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        javax.swing.GroupLayout appointmentsTabLayout = new javax.swing.GroupLayout(appointmentsTab);
        appointmentsTab.setLayout(appointmentsTabLayout);
        appointmentsTabLayout.setHorizontalGroup(
            appointmentsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appointmentsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(appointmentsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(appointmentsTabLayout.createSequentialGroup()
                        .addGroup(appointmentsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createAppointmentBtn)
                            .addGroup(appointmentsTabLayout.createSequentialGroup()
                                .addComponent(aDateSeach)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(aDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(aClientSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(aClientField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(aPetSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(aPetField, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(aSearchBtn)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(appointmentTableScroll, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        appointmentsTabLayout.setVerticalGroup(
            appointmentsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(appointmentsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createAppointmentBtn)
                .addGap(18, 18, 18)
                .addGroup(appointmentsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aDateSeach)
                    .addComponent(aClientSearch)
                    .addComponent(aPetSearch)
                    .addComponent(aSearchBtn)
                    .addComponent(aDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aClientField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aPetField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(appointmentTableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        dashboardTabs.addTab("Appointments", appointmentsTab);

        petsTab.setBackground(new java.awt.Color(255, 255, 255));

        createPetBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        createPetBtn.setText("+ Create New Pet");
        createPetBtn.setToolTipText("");
        createPetBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createPetBtnMouseClicked(evt);
            }
        });

        pNameSearch.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        pNameSearch.setText("Pet Name:");

        pDOBSearch.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        pDOBSearch.setText("Date of Birth:");

        pClientField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        pNameField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        petTableScroll.setBackground(new java.awt.Color(255, 255, 255));

        petTable.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        petTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Pet Name", "Species", "Gender", "Date of Birth", "Client's Last Name", "Actions"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        petTable.setGridColor(new java.awt.Color(255, 255, 255));
        petTableScroll.setViewportView(petTable);
        if (petTable.getColumnModel().getColumnCount() > 0) {
            petTable.getColumnModel().getColumn(0).setResizable(false);
            petTable.getColumnModel().getColumn(1).setResizable(false);
            petTable.getColumnModel().getColumn(2).setResizable(false);
            petTable.getColumnModel().getColumn(3).setResizable(false);
            petTable.getColumnModel().getColumn(4).setResizable(false);
            petTable.getColumnModel().getColumn(5).setResizable(false);
        }

        pClientSearch.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        pClientSearch.setText("Client:");

        pDOBField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        pSearchBtn.setBackground(new java.awt.Color(255, 255, 255));
        pSearchBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        pSearchBtn.setText("Search");

        javax.swing.GroupLayout petsTabLayout = new javax.swing.GroupLayout(petsTab);
        petsTab.setLayout(petsTabLayout);
        petsTabLayout.setHorizontalGroup(
            petsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(petsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(petsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(petsTabLayout.createSequentialGroup()
                        .addComponent(createPetBtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(petsTabLayout.createSequentialGroup()
                        .addComponent(pNameSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pClientSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pClientField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pDOBSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pDOBField, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(pSearchBtn))
                    .addComponent(petTableScroll, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        petsTabLayout.setVerticalGroup(
            petsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(petsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createPetBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(petsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pNameSearch)
                    .addComponent(pClientSearch)
                    .addComponent(pDOBSearch)
                    .addComponent(pSearchBtn)
                    .addComponent(pNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pClientField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pDOBField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(petTableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        dashboardTabs.addTab("Pets", petsTab);

        clientsTab.setBackground(new java.awt.Color(255, 255, 255));

        clientTableScroll.setBackground(new java.awt.Color(255, 255, 255));

        clientsTable.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        clientsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "Email Address", "Phone Number", "Actions"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        clientsTable.setGridColor(new java.awt.Color(255, 255, 255));
        clientTableScroll.setViewportView(clientsTable);
        if (clientsTable.getColumnModel().getColumnCount() > 0) {
            clientsTable.getColumnModel().getColumn(0).setResizable(false);
            clientsTable.getColumnModel().getColumn(1).setResizable(false);
            clientsTable.getColumnModel().getColumn(2).setResizable(false);
            clientsTable.getColumnModel().getColumn(3).setResizable(false);
            clientsTable.getColumnModel().getColumn(4).setResizable(false);
        }

        createClientBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        createClientBtn.setText("+ Create New Client");
        createClientBtn.setToolTipText("");

        cNameSearch.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cNameSearch.setText("Last Name:");

        cEmailSearch.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cEmailSearch.setText("Email:");

        cNumberSearch.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cNumberSearch.setText("Phone:");

        cSearchBtn.setBackground(new java.awt.Color(255, 255, 255));
        cSearchBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        cSearchBtn.setText("Search");

        cNameField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        cEmailField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        cNumberField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        javax.swing.GroupLayout clientsTabLayout = new javax.swing.GroupLayout(clientsTab);
        clientsTab.setLayout(clientsTabLayout);
        clientsTabLayout.setHorizontalGroup(
            clientsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clientsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clientTableScroll)
                    .addGroup(clientsTabLayout.createSequentialGroup()
                        .addGroup(clientsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createClientBtn)
                            .addGroup(clientsTabLayout.createSequentialGroup()
                                .addComponent(cNameSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cEmailSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cNumberSearch)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cNumberField, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(cSearchBtn)))
                .addContainerGap())
        );
        clientsTabLayout.setVerticalGroup(
            clientsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createClientBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(clientsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cNameSearch)
                    .addComponent(cEmailSearch)
                    .addComponent(cNumberSearch)
                    .addComponent(cSearchBtn)
                    .addComponent(cNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(clientTableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        dashboardTabs.addTab("Clients", clientsTab);

        logoutBtn.setBackground(new java.awt.Color(255, 255, 255));
        logoutBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        logoutBtn.setText("Logout");

        javax.swing.GroupLayout dashboardPanelLayout = new javax.swing.GroupLayout(dashboardPanel);
        dashboardPanel.setLayout(dashboardPanelLayout);
        dashboardPanelLayout.setHorizontalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutBtn)
                .addContainerGap())
        );
        dashboardPanelLayout.setVerticalGroup(
            dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dashboardTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        dashboardTabs.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createPetBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createPetBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_createPetBtnMouseClicked

    private void createAppointmentBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createAppointmentBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_createAppointmentBtnMouseClicked

    private void aSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aSearchBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aSearchBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardsGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardsGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardsGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardsGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardsGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aClientField;
    private javax.swing.JLabel aClientSearch;
    private javax.swing.JTextField aDateField;
    private javax.swing.JLabel aDateSeach;
    private javax.swing.JTextField aPetField;
    private javax.swing.JLabel aPetSearch;
    private javax.swing.JButton aSearchBtn;
    private javax.swing.JScrollPane appointmentTableScroll;
    private javax.swing.JPanel appointmentsTab;
    private javax.swing.JTable appointmentsTable;
    private javax.swing.JTextField cEmailField;
    private javax.swing.JLabel cEmailSearch;
    private javax.swing.JTextField cNameField;
    private javax.swing.JLabel cNameSearch;
    private javax.swing.JTextField cNumberField;
    private javax.swing.JLabel cNumberSearch;
    private javax.swing.JButton cSearchBtn;
    private javax.swing.JScrollPane clientTableScroll;
    private javax.swing.JPanel clientsTab;
    private javax.swing.JTable clientsTable;
    private javax.swing.JButton createAppointmentBtn;
    private javax.swing.JButton createClientBtn;
    private javax.swing.JButton createPetBtn;
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.JTabbedPane dashboardTabs;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JTextField pClientField;
    private javax.swing.JLabel pClientSearch;
    private javax.swing.JTextField pDOBField;
    private javax.swing.JLabel pDOBSearch;
    private javax.swing.JTextField pNameField;
    private javax.swing.JLabel pNameSearch;
    private javax.swing.JButton pSearchBtn;
    private javax.swing.JTable petTable;
    private javax.swing.JScrollPane petTableScroll;
    private javax.swing.JPanel petsTab;
    // End of variables declaration//GEN-END:variables

}
