/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vetportal;

import javax.swing.*;
import java.awt.*;

public class AddPet extends JFrame {

    /**
     * Creates new form AddPet()
     */
    public AddPet() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addPetPanel = new JPanel();
        cancelBtn = new JButton();
        submitBtn = new JButton();
        addPetLabel = new JLabel();
        petNameLabel = new JLabel();
        clientNameLabel = new JLabel();
        speciesLabel = new JLabel();
        genderLabel = new JLabel();
        petNameField = new JTextField();
        clientNameField = new JTextField();
        cancelInstructionLabel = new JLabel();
        speciesDropDown = new JComboBox<>();
        genderDropDown = new JComboBox<>();
        dobLabel = new JLabel();
        dobField = new JFormattedTextField();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        addPetPanel.setBackground(new Color(255, 255, 255));

        cancelBtn.setBackground(new Color(255, 255, 255));
        cancelBtn.setFont(new Font("Calibri", 1, 18)); // NOI18N
        cancelBtn.setText("Cancel");

        submitBtn.setBackground(new Color(255, 255, 255));
        submitBtn.setFont(new Font("Calibri", 1, 18)); // NOI18N
        submitBtn.setText("Submit");

        addPetLabel.setBackground(new Color(255, 255, 255));
        addPetLabel.setFont(new Font("Calibri", 0, 18)); // NOI18N
        addPetLabel.setText("Fill out the form below to add new pet");
        addPetLabel.setMaximumSize(new Dimension(74, 200));
        addPetLabel.setMinimumSize(new Dimension(74, 200));

        petNameLabel.setFont(new Font("Calibri", 0, 18)); // NOI18N
        petNameLabel.setText("Pet Name");

        clientNameLabel.setFont(new Font("Calibri", 0, 18)); // NOI18N
        clientNameLabel.setText("Client Name");

        speciesLabel.setFont(new Font("Calibri", 0, 18)); // NOI18N
        speciesLabel.setText("Species");

        genderLabel.setFont(new Font("Calibri", 0, 18)); // NOI18N
        genderLabel.setText("Gender");

        petNameField.setFont(new Font("Calibri", 0, 18)); // NOI18N

        clientNameField.setEditable(false);
        clientNameField.setFont(new Font("Calibri", 0, 18)); // NOI18N

        cancelInstructionLabel.setBackground(new Color(255, 255, 255));
        cancelInstructionLabel.setFont(new Font("Calibri", 0, 18)); // NOI18N
        cancelInstructionLabel.setText("or cancel to return to Pets Dashboard");
        cancelInstructionLabel.setMaximumSize(new Dimension(74, 200));
        cancelInstructionLabel.setMinimumSize(new Dimension(74, 200));

        speciesDropDown.setEditable(true);
        speciesDropDown.setFont(new Font("Calibri", 0, 18)); // NOI18N
        speciesDropDown.setModel(new DefaultComboBoxModel<>(new String[] { "Dog", "Cat", "Bird", "Small Mammal", "Fish", "Reptile" }));
        speciesDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                speciesDropDownActionPerformed(evt);
            }
        });

        genderDropDown.setEditable(true);
        genderDropDown.setFont(new Font("Calibri", 0, 18)); // NOI18N
        genderDropDown.setModel(new DefaultComboBoxModel<>(new String[] { "F", "M", "FS", "MN" }));

        dobLabel.setFont(new Font("Calibri", 0, 18)); // NOI18N
        dobLabel.setText("Date of Birth");

        dobField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        dobField.setFont(new Font("Calibri", 0, 18)); // NOI18N

        GroupLayout addPetPanelLayout = new GroupLayout(addPetPanel);
        addPetPanel.setLayout(addPetPanelLayout);
        addPetPanelLayout.setHorizontalGroup(
            addPetPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(addPetPanelLayout.createSequentialGroup()
                .addGroup(addPetPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(addPetPanelLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(submitBtn)
                        .addGap(54, 54, 54)
                        .addComponent(cancelBtn))
                    .addGroup(addPetPanelLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(addPetPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(cancelInstructionLabel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(addPetLabel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                    .addGroup(addPetPanelLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(addPetPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addComponent(clientNameLabel)
                            .addComponent(petNameLabel)
                            .addComponent(speciesLabel)
                            .addComponent(genderLabel)
                            .addComponent(dobLabel))
                        .addGap(18, 18, 18)
                        .addGroup(addPetPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                            .addComponent(clientNameField, GroupLayout.Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(petNameField, GroupLayout.Alignment.LEADING)
                            .addComponent(speciesDropDown, GroupLayout.Alignment.LEADING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(genderDropDown, GroupLayout.Alignment.LEADING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addComponent(dobField, GroupLayout.Alignment.LEADING))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        addPetPanelLayout.setVerticalGroup(
            addPetPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(addPetPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(addPetLabel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelInstructionLabel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(addPetPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(petNameLabel)
                    .addComponent(petNameField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addPetPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(clientNameLabel)
                    .addComponent(clientNameField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addPetPanelLayout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(speciesLabel)
                    .addComponent(speciesDropDown, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPetPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(genderLabel)
                    .addComponent(genderDropDown, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addPetPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(dobLabel)
                    .addComponent(dobField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(addPetPanelLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(submitBtn)
                    .addComponent(cancelBtn))
                .addGap(126, 126, 126))
        );

        addPetLabel.getAccessibleContext().setAccessibleName("");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(addPetPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(addPetPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void speciesDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_speciesDropDownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_speciesDropDownActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel addPetLabel;
    private JPanel addPetPanel;
    private JButton cancelBtn;
    private JLabel cancelInstructionLabel;
    private JTextField clientNameField;
    private JLabel clientNameLabel;
    private JFormattedTextField dobField;
    private JLabel dobLabel;
    private JComboBox<String> genderDropDown;
    private JLabel genderLabel;
    private JTextField petNameField;
    private JLabel petNameLabel;
    private JComboBox<String> speciesDropDown;
    private JLabel speciesLabel;
    private JButton submitBtn;
    // End of variables declaration//GEN-END:variables
}
