/**
 * File: DashboardsGui.java
 * Date: April 16, 2020
 * @Author: Nour Debiat, Brian Rease, Rebekah Qu
 * Purpose: This window displays the dashboards where users can view appointments, pets, and clients.
 */

package vetportal;

import javax.swing.*;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellEditor;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.EventObject;
import java.util.List;

public class DashboardsGui extends JFrame {

    // Create objects for pages
    VetPortal vetPortal;
    AddClient addClientPage;
    EditClient editClientPage;
    /**
     * Creates new form DashboardsGui
	 * @param vetPortal
	 * @throws ParseException
     */
    public DashboardsGui(VetPortal vetPortal) throws ParseException {
        super("Vet Portal");
        this.vetPortal = vetPortal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() throws ParseException {

        dashboardPanel = new JPanel();
        dashboardTabs = new JTabbedPane();
        appointmentsTab = new JPanel();
        aDateSeach = new javax.swing.JLabel();
        createAppointmentBtn = new javax.swing.JButton();
        aClientSearch = new javax.swing.JLabel();
        aClientField = new javax.swing.JTextField();
        aDateField = new javax.swing.JTextField();
        aSearchBtn = new javax.swing.JButton();
        aPetSearch = new javax.swing.JLabel();
        appointmentTableScroll = new javax.swing.JScrollPane();
        appointmentsTable = new javax.swing.JTable();
        aPetField = new javax.swing.JTextField();
        petsTab = new JPanel();
        createPetBtn = new javax.swing.JButton();
        pNameSearch = new javax.swing.JLabel();
        pDOBSearch = new javax.swing.JLabel();
        pClientField = new javax.swing.JTextField();
        pNameField = new javax.swing.JTextField();
        petTableScroll = new javax.swing.JScrollPane();
        petsTable = new javax.swing.JTable();
        pClientSearch = new javax.swing.JLabel();
        pDOBField = new javax.swing.JTextField();
        pSearchBtn = new javax.swing.JButton();
        clientsTab = new JPanel();
        clientTableScroll = new JScrollPane();
        clientsTable = new JTable();
        createClientBtn = new JButton(new ImageIcon(((new ImageIcon("icons/user-plus.png")).getImage()).getScaledInstance(16, 16, Image.SCALE_SMOOTH)));
        cNameSearch = new JLabel();
        cEmailSearch = new JLabel();
        cNumberSearch = new JLabel();
        cSearchBtn = new JButton(new ImageIcon(((new ImageIcon("icons/search.png")).getImage()).getScaledInstance(16, 16, Image.SCALE_SMOOTH)));
        cNameField = new JTextField();
        cEmailField = new JTextField();
        cNumberField = new JTextField();
        logoutBtn = new JButton(new ImageIcon(((new ImageIcon("icons/sign-out.png")).getImage()).getScaledInstance(16, 16, Image.SCALE_SMOOTH)));

        myClientTableModel = new MyClientTableModel();
        clientTable = new JTable(myClientTableModel);
        clientRenderer = new ClientActionRenderer();
        clientEditor = new ClientActionEditor();
        myPetTableModel = new MyPetTableModel();
        petTable = new JTable(myPetTableModel);
        petRenderer = new PetActionRenderer();
        petEditor = new PetActionEditor();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        dashboardPanel.setBackground(new Color(255, 255, 255));
        dashboardPanel.setForeground(new Color(41, 41, 41));

        dashboardTabs.setBackground(new Color(255, 255, 255));
        dashboardTabs.setForeground(new Color(38, 38, 38));
        dashboardTabs.setFont(new Font("Calibri", 1, 14)); // NOI18N

        appointmentsTab.setBackground(new Color(255, 255, 255));
        appointmentsTab.setFont(new Font("Calibri", 0, 18)); // NOI18N

        aDateSeach.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        aDateSeach.setText("Date:");

        createAppointmentBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        createAppointmentBtn.setText("+ Create New Appointment");
        createAppointmentBtn.setToolTipText("");

        aClientSearch.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        aClientSearch.setText("Client:");

        aClientField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        aDateField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        aSearchBtn.setBackground(new java.awt.Color(255, 255, 255));
        aSearchBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        aSearchBtn.setText("Search");

        aPetSearch.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        aPetSearch.setText("Pet:");

        appointmentTableScroll.setBackground(new java.awt.Color(255, 255, 255));

        appointmentsTable.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        appointmentsTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {},
                new String [] {
                        "Date", "Time", "Client", "Pet", "Reason for Visit", "Actions"
                }
        ) {
            boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        appointmentsTable.setGridColor(new java.awt.Color(255, 255, 255));
        appointmentTableScroll.setViewportView(appointmentsTable);
        if (appointmentsTable.getColumnModel().getColumnCount() > 0) {
            appointmentsTable.getColumnModel().getColumn(0).setResizable(false);
            appointmentsTable.getColumnModel().getColumn(1).setResizable(false);
            appointmentsTable.getColumnModel().getColumn(2).setResizable(false);
            appointmentsTable.getColumnModel().getColumn(3).setResizable(false);
            appointmentsTable.getColumnModel().getColumn(4).setResizable(false);
            appointmentsTable.getColumnModel().getColumn(5).setResizable(false);
        }

        aPetField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        GroupLayout appointmentsTabLayout = new GroupLayout(appointmentsTab);
        appointmentsTab.setLayout(appointmentsTabLayout);
        appointmentsTabLayout.setHorizontalGroup(
                appointmentsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(appointmentsTabLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(appointmentsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(appointmentsTabLayout.createSequentialGroup()
                                                .addGroup(appointmentsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(createAppointmentBtn)
                                                        .addGroup(appointmentsTabLayout.createSequentialGroup()
                                                                .addComponent(aDateSeach)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(aDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(aClientSearch)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(aClientField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(aPetSearch)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(aPetField, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(aSearchBtn)))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(appointmentTableScroll, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addContainerGap())
        );
        appointmentsTabLayout.setVerticalGroup(
                appointmentsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(appointmentsTabLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(createAppointmentBtn)
                                .addGap(18, 18, 18)
                                .addGroup(appointmentsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(aDateSeach)
                                        .addComponent(aClientSearch)
                                        .addComponent(aPetSearch)
                                        .addComponent(aSearchBtn)
                                        .addComponent(aDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(aClientField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(aPetField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(appointmentTableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(70, Short.MAX_VALUE))
        );

        dashboardTabs.addTab("Appointments", appointmentsTab);

        petsTab.setBackground(new Color(255, 255, 255));
        createPetBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        createPetBtn.setText("+ Create New Pet");
        createPetBtn.setToolTipText("");

        pNameSearch.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        pNameSearch.setText("Pet Name:");

        pDOBSearch.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        pDOBSearch.setText("Date of Birth:");

        pClientField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        pNameField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        petTableScroll.setBackground(new java.awt.Color(255, 255, 255));

        petsTable.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        petsTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {},
                new String [] {
                        "Pet Name", "Species", "Gender", "Date of Birth", "Client's Last Name", "Actions"
                }
        ) {
            boolean[] canEdit = new boolean [] {
                    false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        petsTable.setGridColor(new java.awt.Color(255, 255, 255));
        petTableScroll.setViewportView(petTable);
        if (petsTable.getColumnModel().getColumnCount() > 0) {
            petsTable.getColumnModel().getColumn(0).setResizable(false);
            petsTable.getColumnModel().getColumn(1).setResizable(false);
            petsTable.getColumnModel().getColumn(2).setResizable(false);
            petsTable.getColumnModel().getColumn(3).setResizable(false);
            petsTable.getColumnModel().getColumn(4).setResizable(false);
            petsTable.getColumnModel().getColumn(5).setResizable(false);
        }

        pClientSearch.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        pClientSearch.setText("Client:");

        pDOBField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        pSearchBtn.setBackground(new java.awt.Color(255, 255, 255));
        pSearchBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        pSearchBtn.setText("Search");

        GroupLayout petsTabLayout = new GroupLayout(petsTab);
        petsTab.setLayout(petsTabLayout);
        petsTabLayout.setHorizontalGroup(
                petsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(petsTabLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(petsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(petsTabLayout.createSequentialGroup()
                                                .addComponent(createPetBtn)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(petsTabLayout.createSequentialGroup()
                                                .addComponent(pNameSearch)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(pNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(pClientSearch)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(pClientField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(pDOBSearch)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(pDOBField, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                                .addGap(18, 18, 18)
                                                .addComponent(pSearchBtn))
                                        .addComponent(petTableScroll, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addContainerGap())
        );
        petsTabLayout.setVerticalGroup(
                petsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(petsTabLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(createPetBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(petsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(pNameSearch)
                                        .addComponent(pClientSearch)
                                        .addComponent(pDOBSearch)
                                        .addComponent(pSearchBtn)
                                        .addComponent(pNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pClientField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(pDOBField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(petTableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(75, Short.MAX_VALUE))
        );

        dashboardTabs.addTab("Pets", petsTab);

        clientsTab.setBackground(new Color(255, 255, 255));

        clientTable.getColumnModel().getColumn(4).setCellRenderer(clientRenderer);
        clientTable.getColumnModel().getColumn(4).setCellEditor(clientEditor);
        clientTable.setRowHeight(clientRenderer.getTableCellRendererComponent(clientTable, null, true, true, 0, 0).getPreferredSize().height);

        petTable.getColumnModel().getColumn(5).setCellRenderer(petRenderer);
        petTable.getColumnModel().getColumn(5).setCellEditor(petEditor);
        petTable.setRowHeight(petRenderer.getTableCellRendererComponent(petTable, null, true, true, 0, 0).getPreferredSize().height);

        clientTableScroll.setBackground(new Color(255, 255, 255));

        clientsTable.setFont(new Font("Calibri", 0, 14)); // NOI18N
        clientsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {},
            new String [] {
                "First Name", "Last Name", "Email Address", "Phone Number", "Actions"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        clientsTable.setGridColor(new Color(255, 255, 255));
        clientTableScroll.setViewportView(clientTable);
        if (clientsTable.getColumnModel().getColumnCount() > 0) {
            clientsTable.getColumnModel().getColumn(0).setResizable(false);
            clientsTable.getColumnModel().getColumn(1).setResizable(false);
            clientsTable.getColumnModel().getColumn(2).setResizable(false);
            clientsTable.getColumnModel().getColumn(3).setResizable(false);
            clientsTable.getColumnModel().getColumn(4).setResizable(false);
        }

        createClientBtn.setFont(new Font("Calibri", 1, 14)); // NOI18N
        createClientBtn.setText("Create New Client");
        createClientBtn.addActionListener(event -> {
            try {
                openCreateClient();
            } catch (ParseException ex) {
                // Do nothing
            }
        });

        cNameSearch.setFont(new Font("Calibri", 0, 14)); // NOI18N
        cNameSearch.setText("Last Name:");

        cEmailSearch.setFont(new Font("Calibri", 0, 14)); // NOI18N
        cEmailSearch.setText("Email:");

        cNumberSearch.setFont(new Font("Calibri", 0, 14)); // NOI18N
        cNumberSearch.setText("Phone:");

        cSearchBtn.setBackground(new Color(255, 255, 255));
        cSearchBtn.setFont(new Font("Calibri", 1, 14)); // NOI18N
        cSearchBtn.setText("Search");

        cNameField.setFont(new Font("Calibri", 0, 14)); // NOI18N

        cEmailField.setFont(new Font("Calibri", 0, 14)); // NOI18N

        cNumberField.setFont(new Font("Calibri", 0, 14)); // NOI18N

        GroupLayout clientsTabLayout = new GroupLayout(clientsTab);
        clientsTab.setLayout(clientsTabLayout);
        clientsTabLayout.setHorizontalGroup(
            clientsTabLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(clientsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clientsTabLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(clientTableScroll)
                    .addGroup(clientsTabLayout.createSequentialGroup()
                        .addGroup(clientsTabLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(createClientBtn)
                            .addGroup(clientsTabLayout.createSequentialGroup()
                                .addComponent(cNameSearch)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cNameField, GroupLayout.PREFERRED_SIZE, 117, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cEmailSearch)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cEmailField, GroupLayout.PREFERRED_SIZE, 133, GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cNumberSearch)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cNumberField, GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)))
                        .addGap(18, 18, 18)
                        .addComponent(cSearchBtn)))
                .addContainerGap())
        );
        clientsTabLayout.setVerticalGroup(
            clientsTabLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(clientsTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createClientBtn)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(clientsTabLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(cNameSearch)
                    .addComponent(cEmailSearch)
                    .addComponent(cNumberSearch)
                    .addComponent(cSearchBtn)
                    .addComponent(cNameField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(cEmailField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(cNumberField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(clientTableScroll, GroupLayout.PREFERRED_SIZE, 261, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        dashboardTabs.addTab("Clients", clientsTab);

        logoutBtn.setBackground(new Color(255, 255, 255));
        logoutBtn.setFont(new Font("Calibri", 1, 14)); // NOI18N
        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(event -> logout());

        GroupLayout dashboardPanelLayout = new GroupLayout(dashboardPanel);
        dashboardPanel.setLayout(dashboardPanelLayout);
        dashboardPanelLayout.setHorizontalGroup(
            dashboardPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(dashboardTabs, GroupLayout.PREFERRED_SIZE, 700, GroupLayout.PREFERRED_SIZE)
            .addGroup(GroupLayout.Alignment.TRAILING, dashboardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutBtn)
                .addContainerGap())
        );
        dashboardPanelLayout.setVerticalGroup(
            dashboardPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, dashboardPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutBtn)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dashboardTabs, GroupLayout.PREFERRED_SIZE, 450, GroupLayout.PREFERRED_SIZE))
        );

        dashboardTabs.getAccessibleContext().setAccessibleName("");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(dashboardPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addComponent(dashboardPanel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Handler for deleteing a client
    private void deleteSelectedClient(String phoneNumber, String firstName, String lastName) {
        // Ask the user to confirm client deletion      
        int delete = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete " + firstName + " " + lastName + "?", "Confirm Client Deletion", JOptionPane.YES_NO_OPTION);
        // If Yes (0) was selected
        if (delete == 0) {
            // Delete the client
            vetPortal.deleteClient(phoneNumber, firstName, lastName);
            myClientTableModel.remove();
        }
        // If No (1) was selected do nothing

    } //end of deleteSelectedClient()

    // Handler for logout button click event
    private void logout() {
        // Open Login Page
        vetPortal = new VetPortal();
        vetPortal.setVisible(true);
        // Close Vet Portal Dashboard
        dispose();
    }

    // Handler for create client button click event
    private void openCreateClient() throws ParseException {
	// Open the Add Client Page
        addClientPage = new AddClient(vetPortal);
        addClientPage.setVisible(true);        
    }

    // Handler for edit selected client click event
    private void editSelectedClient(String currentFirstName, String currentLastName, String currentEmail, String currentPhoneNumber) throws ParseException {
        // Open the Edit Client Page and pass the selected client's information
        editClientPage = new EditClient(vetPortal, currentFirstName, currentLastName, currentEmail, currentPhoneNumber);
        editClientPage.setVisible(true);
    }
    
    public JTable getClientsTable() {
        return clientsTable;
    }

    public JTable getClientTable() {
        return clientTable;
    }

    public JTable getPetsTable() {
        return petsTable;
    }

    public JTable getPetTable() {
        return petTable;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aClientField;
    private javax.swing.JLabel aClientSearch;
    private javax.swing.JTextField aDateField;
    private javax.swing.JLabel aDateSeach;
    private javax.swing.JTextField aPetField;
    private javax.swing.JLabel aPetSearch;
    private javax.swing.JButton aSearchBtn;
    private javax.swing.JScrollPane appointmentTableScroll;
    private javax.swing.JPanel appointmentsTab;
    private javax.swing.JTable appointmentsTable;
    private javax.swing.JTextField cEmailField;
    private javax.swing.JLabel cEmailSearch;
    private javax.swing.JTextField cNameField;
    private javax.swing.JLabel cNameSearch;
    private javax.swing.JTextField cNumberField;
    private javax.swing.JLabel cNumberSearch;
    private javax.swing.JButton cSearchBtn;
    private javax.swing.JScrollPane clientTableScroll;
    private javax.swing.JPanel clientsTab;
    private javax.swing.JTable clientsTable;
    private javax.swing.JButton createAppointmentBtn;
    private javax.swing.JButton createClientBtn;
    private javax.swing.JButton createPetBtn;
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.JTabbedPane dashboardTabs;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JTextField pClientField;
    private javax.swing.JLabel pClientSearch;
    private javax.swing.JTextField pDOBField;
    private javax.swing.JLabel pDOBSearch;
    private javax.swing.JTextField pNameField;
    private javax.swing.JLabel pNameSearch;
    private javax.swing.JButton pSearchBtn;
    private javax.swing.JTable petsTable;
    private javax.swing.JScrollPane petTableScroll;
    private javax.swing.JPanel petsTab;


    //Objects for Client Table
    private MyClientTableModel myClientTableModel;
    private JTable clientTable;
    private ClientActionRenderer clientRenderer;
    private ClientActionEditor clientEditor;

    //Objects for Pet Table
    private MyPetTableModel myPetTableModel;
    private JTable petTable;
    private PetActionRenderer petRenderer;
    private PetActionEditor petEditor;
    // End of variables declaration//GEN-END:variables

    // Action Pane for Clients Table
    public class ClientActionPane extends JPanel {

        private JButton editButton;
        private JButton deleteButton;

        public ClientActionPane() {
            setLayout(new GridBagLayout());
            // Add icons and tool tips to buttons
            editButton = new JButton(new ImageIcon(((new ImageIcon("icons/edit.png")).getImage()).getScaledInstance(16, 16, Image.SCALE_SMOOTH)));
            editButton.setToolTipText("Edit Client");
            deleteButton = new JButton(new ImageIcon(((new ImageIcon("icons/trash.png")).getImage()).getScaledInstance(16, 16, Image.SCALE_SMOOTH)));
            deleteButton.setToolTipText("Delete Client");

            add(editButton);
            add(deleteButton);
                    
            editButton.addActionListener(event -> edit());
            deleteButton.addActionListener(event -> delete());            
        } //end of constructor

        public void addActionListener(ActionListener listener) {
            editButton.addActionListener(listener);
            deleteButton.addActionListener(listener);
        }
        
        private void edit() {
            // Get the information for the selected client
            Object selectedFirstName = myClientTableModel.getValueAt(clientTable.getSelectedRow(), 0);
            Object selectedLastName = myClientTableModel.getValueAt(clientTable.getSelectedRow(), 1);
            Object selectedEmail = myClientTableModel.getValueAt(clientTable.getSelectedRow(), 2);
            Object selectedPhoneNumber = myClientTableModel.getValueAt(clientTable.getSelectedRow(), 3);
            try {
                // Pass to the event handler
                editSelectedClient((String) selectedFirstName, (String) selectedLastName, (String) selectedEmail, (String) selectedPhoneNumber);
            } catch (ParseException ex) {
                // DO nothing
            }
        }          

        private void delete() {
            Object selectedPhoneNumber = myClientTableModel.getValueAt(clientTable.getSelectedRow(), 3);
            Object selectedFirstName = myClientTableModel.getValueAt(clientTable.getSelectedRow(), 0);
            Object selectedLastName = myClientTableModel.getValueAt(clientTable.getSelectedRow(), 1);
            deleteSelectedClient((String) selectedPhoneNumber, (String) selectedFirstName, (String) selectedLastName);
            myClientTableModel.remove();
        }      
        
    } //end of ActionPane

    public class MyClientTableModel extends AbstractTableModel {

        private  List<Clients> clientData;

        public MyClientTableModel() {
            clientData = new ArrayList<>(25);
        }

        public List<Clients> getClientData() {
            return clientData;
        }

        @Override
        public String getColumnName(int column) {
            String value = null;
            switch (column) {
                case 0:
                    value = "First Name";
                    break;
                case 1:
                    value = "Last Name";
                    break;
                case 2:
                    value = "Email Address";
                    break;
                case 3:
                    value = "Phone Number";
                    break;
                case 4:
                    value = "Actions";
                    break;
            }
            return value;
        }

        @Override
        public Class<?> getColumnClass(int columnIndex) {
            Class value = Object.class;
            switch (columnIndex) {
                case 0:
                case 1:
                case 2:
                case 3:
                    value = String.class;
                    break;
            }
            return value;
        }

        @Override
        public int getRowCount() {
            return clientData.size();
        }

        @Override
        public int getColumnCount() {
            return 5;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            Clients obj = clientData.get(rowIndex);
            String value = null;
            switch (columnIndex) {
                case 0:
                    value = obj.getClientFirstName();
                    break;
                case 1:
                    value = obj.getClientLastName();
                    break;
                case 2:
                    value = obj.getClientEmail();
                    break;
                case 3:
                    value = obj.getClientPhoneNumber();
                    break;
            }
            return value;
        }

        public void add(Clients content) {
            int startIndex = getRowCount();
            clientData.add(content);
            fireTableRowsInserted(startIndex, getRowCount() - 1);
        }

        public void remove() {
            clientData.clear();
            fireTableDataChanged();
            vetPortal.viewAllClients();
        }

        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return columnIndex == 4;
        }
    } //end of MyTableModel

    public class ClientActionRenderer extends DefaultTableCellRenderer {

        private ClientActionPane clientActionPane;

        public ClientActionRenderer() {
            clientActionPane = new ClientActionPane();
        }

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            return clientActionPane;
        }
    } //end of DefaultTableCellRenderer

    public class ClientActionEditor extends AbstractCellEditor implements TableCellEditor {

        private ClientActionPane clientActionPane;

        public ClientActionEditor() {
            clientActionPane = new ClientActionPane();
            clientActionPane.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    SwingUtilities.invokeLater(new Runnable() {
                        @Override
                        public void run() {
                            stopCellEditing();
                        }
                    });
                }
            });
        }

        @Override
        public Object getCellEditorValue() {
            return null;
        }

        @Override
        public boolean isCellEditable(EventObject e) {
            return true;
        }

        @Override
        public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int column) {
            return clientActionPane;
        }
    } //end of AbstractCellEditor

    //TODO: Finish code below here:

    // Action Pane for Pets Table
    public class PetActionPane extends JPanel {

        private JButton editButton;
        private JButton deleteButton;

        public PetActionPane() {
            setLayout(new GridBagLayout());
            // Add icons and tool tips to buttons
            editButton = new JButton(new ImageIcon(((new ImageIcon("icons/edit.png")).getImage()).getScaledInstance(16, 16, Image.SCALE_SMOOTH)));
            editButton.setToolTipText("Edit Client");
            deleteButton = new JButton(new ImageIcon(((new ImageIcon("icons/trash.png")).getImage()).getScaledInstance(16, 16, Image.SCALE_SMOOTH)));
            deleteButton.setToolTipText("Delete Client");

            add(editButton);
            add(deleteButton);

            editButton.addActionListener(event -> edit());
            deleteButton.addActionListener(event -> delete());
        } //end of constructor

        public void addActionListener(ActionListener listener) {
            editButton.addActionListener(listener);
            deleteButton.addActionListener(listener);
        }

        private void edit() {

        }

        private void delete() {

        }

    } //end of ActionPane

    public class MyPetTableModel extends AbstractTableModel {

        private  List<Pets> petData;

        public MyPetTableModel() {
            petData = new ArrayList<>(25);
        }

        public List<Pets> getPetData() {
            return petData;
        }

        @Override
        public String getColumnName(int column) {
            String value = null;
            switch (column) {
                case 0:
                    value = "Pet Name";
                    break;
                case 1:
                    value = "Species";
                    break;
                case 2:
                    value = "Gender";
                    break;
                case 3:
                    value = "Date of Birth";
                    break;
                case 4:
                    value = "Client's Last Name";
                    break;
                case 5:
                    value = "Actions";
                    break;
            }
            return value;
        }

        @Override
        public Class<?> getColumnClass(int columnIndex) {
            Class value = Object.class;
            switch (columnIndex) {
                case 0:
                case 1:
                case 2:
                case 3:
                case 4:
                    value = String.class;
                    break;
            }
            return value;
        }

        @Override
        public int getRowCount() {
            return petData.size();
        }

        @Override
        public int getColumnCount() {
            return 6;
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            Pets obj = petData.get(rowIndex);

            int petOwnerID = obj.getPetOwner();
            vetPortal.getVetDatabase().open();
            String clientLastName = vetPortal.getVetDatabase().getClientLastName(petOwnerID);
            vetPortal.getVetDatabase().close();

            String value = null;
            switch (columnIndex) {
                case 0:
                    value = obj.getPetName();
                    break;
                case 1:
                    value = obj.getPetSpecies();
                    break;
                case 2:
                    value = obj.getPetGender();
                    break;
                case 3:
                    value = obj.getPetDateOfBirth();
                    break;
                case 4:
                    value = clientLastName;
            }
            return value;
        }

        public void add(Pets content) {
            int startIndex = getRowCount();
            petData.add(content);
            fireTableRowsInserted(startIndex, getRowCount() - 1);
        }

        public void remove() {
            petData.clear();
            fireTableDataChanged();
            vetPortal.viewAllPets();
        }

        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return columnIndex == 5;
        }
    } //end of MyTableModel

    public class PetActionRenderer extends DefaultTableCellRenderer {

        private PetActionPane petActionPane;

        public PetActionRenderer() {
            petActionPane = new PetActionPane();
        }

        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            return petActionPane;
        }
    } //end of DefaultTableCellRenderer

    public class PetActionEditor extends AbstractCellEditor implements TableCellEditor {

        private PetActionPane petActionPane;

        public PetActionEditor() {
            petActionPane = new PetActionPane();
            petActionPane.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    SwingUtilities.invokeLater(new Runnable() {
                        @Override
                        public void run() {
                            stopCellEditing();
                        }
                    });
                }
            });
        }

        @Override
        public Object getCellEditorValue() {
            return null;
        }

        @Override
        public boolean isCellEditable(EventObject e) {
            return true;
        }

        @Override
        public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int column) {
            return petActionPane;
        }
    } //end of AbstractCellEditor

} //end of DashboardsGui