/**
 * File: DashboardsGui.java
 * Date: April 16, 2020
 * @Author: Nour Debiat
 * Purpose: This window displays the dashboards where users can view appointments, pets, and clients.
 */

package vetportal;

import javax.swing.*;
import java.text.ParseException;

public class DashboardsGui extends javax.swing.JFrame {

    //Create object for VetPortal and AddClient page:
    VetPortal vetPortal;
    AddClient addClient2Page;
    /**
     * Creates new form DashboardsGui
     */
    public DashboardsGui(VetPortal vetPortal) throws ParseException {
        super("Vet Portal");
        this.vetPortal = vetPortal;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() throws ParseException {

        dashboardPanel = new javax.swing.JPanel();
        dashboardTabs = new javax.swing.JTabbedPane();
        appointmentsTab = new javax.swing.JPanel();
        petsTab = new javax.swing.JPanel();
        clientsTab = new javax.swing.JPanel();
        clientTableScroll = new javax.swing.JScrollPane();
        clientsTable = new javax.swing.JTable();
        createClientBtn = new javax.swing.JButton();
        cNameSearch = new javax.swing.JLabel();
        cEmailSearch = new javax.swing.JLabel();
        cNumberSearch = new javax.swing.JLabel();
        cSearchBtn = new javax.swing.JButton();
        cNameField = new javax.swing.JTextField();
        cEmailField = new javax.swing.JTextField();
        cNumberField = new javax.swing.JTextField();
        logoutBtn = new javax.swing.JButton();

        //table buttons
        cDeleteBtn = new javax.swing.JButton();
        cEditBtn = new javax.swing.JButton();
        cButtonsGroup = new javax.swing.ButtonGroup();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dashboardPanel.setBackground(new java.awt.Color(255, 255, 255));
        dashboardPanel.setForeground(new java.awt.Color(41, 41, 41));

        dashboardTabs.setBackground(new java.awt.Color(255, 255, 255));
        dashboardTabs.setForeground(new java.awt.Color(38, 38, 38));
        dashboardTabs.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N

        appointmentsTab.setBackground(new java.awt.Color(255, 255, 255));
        appointmentsTab.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        javax.swing.GroupLayout appointmentsTabLayout = new javax.swing.GroupLayout(appointmentsTab);
        appointmentsTab.setLayout(appointmentsTabLayout);
        appointmentsTabLayout.setHorizontalGroup(
                appointmentsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 695, Short.MAX_VALUE)
        );
        appointmentsTabLayout.setVerticalGroup(
                appointmentsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 419, Short.MAX_VALUE)
        );

        dashboardTabs.addTab("Appointments", appointmentsTab);

        petsTab.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout petsTabLayout = new javax.swing.GroupLayout(petsTab);
        petsTab.setLayout(petsTabLayout);
        petsTabLayout.setHorizontalGroup(
                petsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 695, Short.MAX_VALUE)
        );
        petsTabLayout.setVerticalGroup(
                petsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 419, Short.MAX_VALUE)
        );

        dashboardTabs.addTab("Pets", petsTab);

        clientsTab.setBackground(new java.awt.Color(255, 255, 255));

        clientTableScroll.setBackground(new java.awt.Color(255, 255, 255));

        clientsTable.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        clientsTable.setModel(new javax.swing.table.DefaultTableModel(null,
                new String [] {
                        "First Name", "Last Name", "Email Address", "Phone Number", "Actions"
                }
        ) {
            boolean[] canEdit = new boolean [] {
                    false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        clientsTable.setGridColor(new java.awt.Color(255, 255, 255));
        clientTableScroll.setViewportView(clientsTable);
        if (clientsTable.getColumnModel().getColumnCount() > 0) {
            clientsTable.getColumnModel().getColumn(0).setResizable(false);
            clientsTable.getColumnModel().getColumn(1).setResizable(false);
            clientsTable.getColumnModel().getColumn(2).setResizable(false);
            clientsTable.getColumnModel().getColumn(3).setResizable(false);
            clientsTable.getColumnModel().getColumn(4).setResizable(false);
        }

        createClientBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        createClientBtn.setText("+ Create New");

        cNameSearch.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cNameSearch.setText("Last Name:");

        cEmailSearch.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cEmailSearch.setText("Email:");

        cNumberSearch.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        cNumberSearch.setText("Phone:");

        cSearchBtn.setBackground(new java.awt.Color(255, 255, 255));
        cSearchBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        cSearchBtn.setText("Search");

        //table buttons
        cDeleteBtn.setText("Delete");
        cEditBtn.setText("Edit");
        //add buttons to group
        cButtonsGroup.add(cDeleteBtn);
        cButtonsGroup.add(cEditBtn);

        cNameField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        cEmailField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        cNumberField.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        javax.swing.GroupLayout clientsTabLayout = new javax.swing.GroupLayout(clientsTab);
        clientsTab.setLayout(clientsTabLayout);
        clientsTabLayout.setHorizontalGroup(
                clientsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(clientsTabLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(clientsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(clientTableScroll)
                                        .addGroup(clientsTabLayout.createSequentialGroup()
                                                .addGroup(clientsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(createClientBtn)
                                                        .addGroup(clientsTabLayout.createSequentialGroup()
                                                                .addComponent(cNameSearch)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(cNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(cEmailSearch)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(cEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(cNumberSearch)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(cNumberField, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)))
                                                .addGap(18, 18, 18)
                                                .addComponent(cSearchBtn)))
                                .addContainerGap())
        );
        clientsTabLayout.setVerticalGroup(
                clientsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(clientsTabLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(createClientBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(clientsTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cNameSearch)
                                        .addComponent(cEmailSearch)
                                        .addComponent(cNumberSearch)
                                        .addComponent(cSearchBtn)
                                        .addComponent(cNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cEmailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8)
                                .addComponent(clientTableScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(74, Short.MAX_VALUE))
        );

        dashboardTabs.addTab("Clients", clientsTab);

        logoutBtn.setBackground(new java.awt.Color(255, 255, 255));
        logoutBtn.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        logoutBtn.setText("Logout");

        javax.swing.GroupLayout dashboardPanelLayout = new javax.swing.GroupLayout(dashboardPanel);
        dashboardPanel.setLayout(dashboardPanelLayout);
        dashboardPanelLayout.setHorizontalGroup(
                dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dashboardTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(logoutBtn)
                                .addContainerGap())
        );
        dashboardPanelLayout.setVerticalGroup(
                dashboardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(logoutBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addComponent(dashboardTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        dashboardTabs.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dashboardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dashboardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        addClient2Page = new AddClient(vetPortal);
        createClientBtn.addActionListener(event -> addClient2Page.setVisible(true));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JTable getClientsTable() {
        return clientsTable;
    }

    public void setClientsTable(JTable clientsTable) {
        this.clientsTable = clientsTable;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel appointmentsTab;
    private javax.swing.JTextField cEmailField;
    private javax.swing.JLabel cEmailSearch;
    private javax.swing.JTextField cNameField;
    private javax.swing.JLabel cNameSearch;
    private javax.swing.JTextField cNumberField;
    private javax.swing.JLabel cNumberSearch;
    private javax.swing.JButton cSearchBtn;
    private javax.swing.JScrollPane clientTableScroll;
    private javax.swing.JPanel clientsTab;
    private javax.swing.JTable clientsTable;
    private javax.swing.JButton createClientBtn;
    private javax.swing.JPanel dashboardPanel;
    private javax.swing.JTabbedPane dashboardTabs;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPanel petsTab;

    //buttons to add to table
    private javax.swing.JButton cDeleteBtn;
    private javax.swing.JButton cEditBtn;
    //button group
    private javax.swing.ButtonGroup cButtonsGroup;
    // End of variables declaration//GEN-END:variables
}